### ISSUE TITLE
CreateTopicExamples throwing NoSuchMethodError

### ISSUE THREAD

**Issue by argybarg** [GoogleCloudPlatform/java-docs-samples#1109]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/pubsub/cloud-client/src/main/java/com/example/pubsub/CreateTopicExample.java

### Did you change the file? If so, how?

Not qualified.

## Describe the issue

Running the main() as written returns:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:77)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture.<init>(CallbackChainRetryingFuture.java:62)
	at com.google.api.gax.retrying.ScheduledRetryingExecutor.createFuture(ScheduledRetryingExecutor.java:84)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:61)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.pubsub.v1.TopicAdminClient.createTopic(TopicAdminClient.java:250)
	at com.google.cloud.pubsub.v1.TopicAdminClient.createTopic(TopicAdminClient.java:201)
	at PubSub.CreateTopicExample.main(CreateTopicExample.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Followed all instructions as in the [Quickstart Guide](https://cloud.google.com/pubsub/docs/quickstart-client-libraries), verified that Service Account is for Project > Owner. Project ID is coming up as expected in debugging.

**Comment by argybarg** [comment]
With a little more investigation, this seems to be Gradle relying on different dependencies of Guava in its different phases (build, compile, etc.). Being a lazy sort I migrated to Maven and the problem went away (for now). We may still want some notes for the beginner/early intermediate user (such as me) who may find Gradle bringing old JARs into the process.

**Comment by argybarg** [comment]
This seems to come down to a transitive dependency on guava-jdk5. This code snippet in my build.gradle file resolved it:

```
configurations {
    all*.exclude group: 'com.google.guava', module:'guava-jdk5'
}
```

Better, of course, to capture the dependency and rehabilitate it.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 192 days. You may reopen this issue if it has been closed in error.
