### ISSUE TITLE
Permission Denied with service account known to be Project Owner

### ISSUE THREAD

**Issue by argybarg** [GoogleCloudPlatform/java-docs-samples#1111]
## In which file did you encounter the issue?

java-docs-samples/pubsub/cloud-client/src/main/java/com/example/pubsub/CreateTopicExample.java

### Did you change the file? If so, how?

Nope. Don't have a starting point.

## Describe the issue

I'm working in IntelliJ, Maven framework, OSX, Java 8.

I followed all the steps as published in the Quickstart: 

1. Created a service account as Project: Owner.
2. Installed the Gcloud SDK.
3. Set my GOOGLE_APPLICATIONS_CREDENTIALS envvar
4. Found that everything was hunky dory from the command line: I could create topics, publish messages, whatever I wanted.

So, to emphasize, I confirmed that my permissions are set correctly and grant Owner permissions to that service account.

On running the main(), however, the ApiException was "PERMISSION_DENIED." The full stacktrace:

```
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.
    at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55)
    at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
    at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
    at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
    at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)
    at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
    at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
    at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
    at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492)
    at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
    at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
    at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.
    at io.grpc.Status.asRuntimeException(Status.java:526)
    ... 19 more

```

The debugger confirmed that the projectId variable was set to the correct default project for this service account, so it is picking up the correct account, which should, as Owner, have all permissions.

If it helps, the Maven dependency tree:

```
[INFO] groupId:PirateshipClientv2:jar:1.0-SNAPSHOT
[INFO] +- com.google.cloud:google-cloud-pubsub:jar:0.46.0-beta:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.28.0:compile
[INFO] |  |  +- com.google.guava:guava:jar:20.0:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.23.0:compile
[INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.1:compile
[INFO] |  |  +- com.google.api:api-common:jar:1.5.0:compile
[INFO] |  |  +- com.google.api:gax:jar:1.25.0:compile
[INFO] |  |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  |  \- com.google.auth:google-auth-library-oauth2-http:jar:0.9.1:compile
[INFO] |  |  |     \- com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[INFO] |  |  |        \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.5.1:compile
[INFO] |  |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.10.0:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.11.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core-grpc:jar:1.28.0:compile
[INFO] |  |  +- com.google.auth:google-auth-library-credentials:jar:0.9.1:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.5.1:compile
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.10.1:compile
[INFO] |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.10.1:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.10.1:compile
[INFO] |  |  \- com.google.api:gax-grpc:jar:1.25.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:0.11.0:compile
[INFO] |  +- com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:0.11.0:compile
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.10.1:compile
[INFO] |  |  \- io.grpc:grpc-core:jar:1.10.1:compile (version selected from constraint [1.10.1,1.10.1])
[INFO] |  |     +- com.google.errorprone:error_prone_annotations:jar:2.1.2:compile
[INFO] |  |     +- io.opencensus:opencensus-api:jar:0.11.0:compile
[INFO] |  |     \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.11.0:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.10.1:compile
[INFO] |  +- io.grpc:grpc-auth:jar:1.10.1:compile
[INFO] |  \- com.google.auto.value:auto-value:jar:1.4:compile
[INFO] \- org.apache.commons:commons-lang3:jar:3.7:compile
```

Not sure where to proceed from here.

**Comment by argybarg** [comment]
Okay, my fault. IntelliJ was not picking up the environmental variable. It might be worth a courtesy note on the Quickstart to let people know how to pass the environmental variable into IntelliJ/Eclipse. Or not.
