### ISSUE TITLE
urlfetch sample for appengine-java8 does not work

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/java-docs-samples#1225]
Getting this error in the log:
2018-10-05 16:27:57.321 PDT
com.google.apphosting.runtime.jetty9.JettyLogger warn: / (JettyLogger.java:29)
java.io.FileNotFoundException: http://jsonplaceholder.typicode.com/posts/777
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by lesv** [comment]
@averikitsch This used to work, you might wish to take a look.
