### ISSUE TITLE
AutoML: set credentials example from java 

### ISSUE THREAD

**Issue by charbull** [GoogleCloudPlatform/java-docs-samples#1314]
Hello,

Is it possible to provide an example code in Java in order to do the before your begin steps: [[here](https://cloud.google.com/vision/automl/docs/before-you-begin)]

I created a service account and downloaded the json file.
I keep getting unAuthenticated error, 

This is a what I am trying to do:

```Java
ClassLoader classLoader = Trainer.class.getClassLoader();

String path = classLoader.getResource("keys.json").getPath();

GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream(path))
				.createScoped(Collections.singleton(IamScopes.CLOUD_PLATFORM));
		
CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(credentials);
		
AutoMlSettings autoMlSettings = AutoMlSettings.newBuilder().setCredentialsProvider(credentialsProvider).build();
```

The error message:

```
Problem accessing /. Reason:

    Server Error
Caused by:

com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:73)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)

**Comment by charbull** [comment]
it worked after i removed this line from the appengine-web.xml

```
 <url-stream-handler>urlfetch</url-stream-handler>
```
