### ISSUE TITLE
Flaky Healthcare tests

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#1481]
## In which file did you encounter the issue?

healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java

## Describe the issue

[Test Fusion](https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fperiodic/KOKORO/569be8a6-9318-4272-a25b-ad463abef9a4/1561316765710/build%20%2375/Targets?target=github%2Fjava-docs-samples%2Fhealthcare%2Fv1beta1%2Ftarget%2Fsurefire-reports&drilldownTab=tests)

**Comment by gguuss** [comment]
@noerog /FYI

**Comment by lesv** [comment]
```
FhirResourceTests(sponge_log).test_FhirResourceConditionalPatch

Run time 0:00:00.260
Error: Exception patching FHIR resource: HTTP/1.1 404 Not Found
java.lang.RuntimeException:
Exception patching FHIR resource: HTTP/1.1 404 Not Found

	at snippets.healthcare.fhir.resources.FhirResourceConditionalPatch.fhirResourceConditionalPatch(FhirResourceConditionalPatch.java:85)
	at snippets.healthcare.FhirResourceTests.test_FhirResourceConditionalPatch(FhirResourceTests.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

**Comment by noerog** [comment]
I'm looking into this.

**Comment by noerog** [comment]
This is obsolete due to https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2806.
