### ISSUE TITLE
Error while checking the status of a transfer

### ISSUE THREAD

**Issue by maihoanglai** [GoogleCloudPlatform/java-docs-samples#1575]
## In which file did you encounter the issue?
com.google.cloud.storage.storagetransfer.samples.RequestChecker. java

### Did you change the file? If so, how?
Changed **PROJECT_ID** and **JOB_NAME** accordingly. 

## Describe the issue
I followed this tutorial but when I run the last command  to check status of the transfer operation it thrown error. I tried so many ways but couldn't understand what need to be put into JOB_NAME. 
EX: **transferJobs/16721838809310199570**
Command: 

> mvn exec:java -Dexec.mainClass="com.google.cloud.storage.storagetransfer.samples.RequestChecker"

Error:
```

com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "The TransferJob name must be in the pattern of \"transferJobs/[^/]+\".",
    "reason" : "badRequest"
  } ],
  "message" : "The TransferJob name must be in the pattern of \"transferJobs/[^/]+\".",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.cloud.storage.storagetransfer.samples.RequestChecker.checkTransfer(RequestChecker.java:57)
        at com.google.cloud.storage.storagetransfer.samples.RequestChecker.main(RequestChecker.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
```

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/storage/storage-transfer

**Comment by kurtisvg** [comment]
@frankyn - Can you clarify the proper format for the transfer job name?

**Comment by frankyn** [comment]
Hi @maihoanglai,

I ran the sample after updating the constants to the following:
```java
  private static final String PROJECT_ID = "spec-test-ruby-samples";
  private static final String JOB_NAME = "transferJobs/10934963950673229351";
```

I retrieved the transfer Job ID using the API Explorer in documentation (I linked to an example using a filter):
[List TransferService Jobs in project "your-project-id"](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/list?apix_params=%7B%22filter%22%3A%22%7B%5C%22project_id%5C%22%3A%20%5C%22your-project-id%5C%22%7D%22%7D)

After I retrieved the transfer Job ID, I updated the constants with the Job ID and project ID which it's associated to.

The result I saw using my own project:
```
INFO: Result of transferOperations/list: {
  "operations" : [ {
    "done" : true,
    "metadata" : {
      "@type" : "type.googleapis.com/google.storagetransfer.v1.TransferOperation",
      "name" : "transferOperations/transferJobs-10934963950673229351-1542324108074607",
      "projectId" : "spec-test-ruby-samples",
      "transferSpec" : {
        "gcsDataSource" : {
          "bucketName" : "ctlbipxytfldqlpcedll"
        },
        "gcsDataSink" : {
          "bucketName" : "2018-cloud-next"
        },
        "objectConditions" : { },
        "transferOptions" : {
          "deleteObjectsUniqueInSink" : true
        }
      },
      "startTime" : "2018-11-15T23:21:48.107519626Z",
      "endTime" : "2018-11-15T23:22:08.778552657Z",
      "status" : "SUCCESS",
      "counters" : {
        "objectsFoundOnlyFromSink" : "3",
        "bytesFoundOnlyFromSink" : "166292",
        "objectsDeletedFromSink" : "3",
        "bytesDeletedFromSink" : "166292"
      },
      "transferJobName" : "transferJobs/10934963950673229351"
    },
    "name" : "transferOperations/transferJobs-10934963950673229351-1542324108074607",
    "response" : {
      "@type" : "type.googleapis.com/google.protobuf.Empty"
    }
  } ]
}
```

HTH

**Comment by maihoanglai** [comment]
Thank your for your detailed answer @frankyn. 
I did exactly what you did but I still confront with the error I mentioned above. 
I'm not sure the difference between our environments. Did you run your code on Cloud Shell?

**Comment by frankyn** [comment]
No I ran this on my linux environment (Debian based). I might be jumping a step when explaining so I added a list of repro steps to compare against. 

Steps to reproduce:
1. Update RequestChecker constants
```java
  private static final String PROJECT_ID = "spec-test-ruby-samples";
  private static final String JOB_NAME = "transferJobs/10934963950673229351";
```
1. Set environment variable with service account credentials
```bash
export GOOGLE_APPLICATION_CREDENTIALS="path/to/service-account.json"
```
1. Run sample
```bash
mvn exec:java -Dexec.mainClass="com.google.cloud.storage.storagetransfer.samples.RequestChecker"
```

**Comment by maihoanglai** [comment]
@frankyn 
Thank for your very detailed repro steps. 
I did the same as steps you mentioned. The difference that I can think of is just the running environment. Let me try and get back to you the result when I reach the office tomorrow. Thanks.

**Comment by frankyn** [comment]
Thanks for the follow-up. Please keep me posted. I'm happy to continue debugging.

**Comment by kurtisvg** [comment]
Closing this out since it's been over 30 days with no response.
