### ISSUE TITLE
getting the error to fetch time service data for metric

### ISSUE THREAD

**Issue by madhubkk** [GoogleCloudPlatform/java-docs-samples#1579]
Sep 12, 2019 6:50:51 PM com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
Exception in thread "main" java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:132)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:115)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:88)
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:67)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:140)
	at com.google.cloud.monitoring.v3.stub.GrpcMetricServiceStub.create(GrpcMetricServiceStub.java:176)
	at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings.createStub(MetricServiceStubSettings.java:187)
	at com.google.cloud.monitoring.v3.MetricServiceClient.<init>(MetricServiceClient.java:157)
	at com.google.cloud.monitoring.v3.MetricServiceClient.create(MetricServiceClient.java:138)
	at com.google.cloud.monitoring.v3.MetricServiceClient.create(MetricServiceClient.java:129)
	at com.example.monitoring.QuickstartSample.main(QuickstartSample.java:51)

**Comment by averikitsch** [comment]
Hi @madhubkk, can you provide us with more information on what you are trying to do and how you got this error? From the error it looks like you need to set your env var GOOGLE_APPLICATION_CREDENTIALS. Learn how here: [Obtaining and providing service account credentials](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually).

**Comment by averikitsch** [comment]
Please feel free to reopen this issue if your problem continues persist.
