### ISSUE TITLE
How to solve the exception when ClientStream<StreamingRecognizeRequest> create & closeSend frequentlly?

### ISSUE THREAD

**Issue by hlguo** [GoogleCloudPlatform/java-docs-samples#1631]
my code is as below:
```java
    public void sendNext(byte[] bytes){
        // Subsequent requests must **only** contain the audio data.
        request = StreamingRecognizeRequest.newBuilder()
                .setAudioContent(ByteString.copyFrom(bytes))
                .build();
        clientStream.send(request);
    }
    public void closeSend() throws Exception {
        clientStream.closeSend();
        System.out.println("speak stop time: " + getTimeString());
    }

    public void startSend() {
        System.out.println("Start time: " + getTimeString());
        clientStream = client.streamingRecognizeCallable().splitCall(responseObserver);
        request = StreamingRecognizeRequest.newBuilder()
                .setStreamingConfig(streamingRecognitionConfig)
                .build(); // The first request in a streaming call has to be a config
        clientStream.send(request);
    }
```

before sent audio stream startSend() will be called, then sendNext(byte[] bytes) will be called many times to send audio stream, after the speak end, closeSend() will be called. 
then start next speek, startSend() will be called again... then sendNext(byte[] bytes), then closeSend().

when run this, the below exception will be poped:
```
java.lang.IllegalStateException: call was half-closed
        at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
        at io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:466)
        at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:457)
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
        at com.google.api.gax.grpc.GrpcDirectBidiStreamingCallable$1.send(GrpcDirectBidiStreamingCallable.java:67)
        at com.google.api.gax.tracing.TracedBidiCallable$TracingClientStream.send(TracedBidiCallable.java:132)
        at com.tuge.translator.StreamingMicRecognize.sendNext(StreamingMicRecognize.java:96)
        at com.tuge.translator.Translator.handleMessage(Translator.java:103)
        at com.tuge.translator.Translator$1.onAudioData(Translator.java:239)

&

com.google.api.gax.rpc.OutOfRangeException: io.grpc.StatusRuntimeException: OUT_OF_RANGE: Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:63)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
        at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
        at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
        at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: OUT_OF_RANGE: Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.
        at io.grpc.Status.asRuntimeException(Status.java:533)
        ... 24 more
```

how to solve these exceptions? maybe I should add some code to closeSend after clientStream.closeSend();  to wait the clientStream close?

**Comment by hlguo** [comment]
I modify the code as below:


 public void sendNext(byte[] bytes)
    {
        // Subsequent requests must **only** contain the audio data.
        if(clientStream.isSendReady())
        {
            request = StreamingRecognizeRequest.newBuilder()
                    .setAudioContent(ByteString.copyFrom(bytes))
                    .build();
            clientStream.send(request);
        }
    }

the exception java.lang.IllegalStateException: call was half-closed disappeared, but the exception 
com.google.api.gax.rpc.OutOfRangeException: io.grpc.StatusRuntimeException: OUT_OF_RANGE: Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time.
always poped up, how to solve this problem?
after I call clientStream.closeSend(); the status is not OK? how to set the status ?

**Comment by nnegrey** [comment]
Once the `clientStream` is closed or in this case half closed, you can not use it to send any more info. 

From the error it seems like some `sendData` call is happening after you closed the stream and before you open a new one.
