### ISSUE TITLE
spanner: "Could not find policy 'pick_first'" when running "Getting started with Cloud Spanner in Java" guide

### ISSUE THREAD

**Issue by skuruppu** [GoogleCloudPlatform/java-docs-samples#2061]
## In which file did you encounter the issue?

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/spanner/cloud-client/pom.xml

### Did you change the file? If so, how?

No

## Describe the issue

When you follow the steps at [Getting started with Cloud Spanner in Java](https://cloud.google.com/spanner/docs/getting-started/java/), I'm unable to run the samples because I get the following error:

```
$ java -jar target/spanner-google-cloud-samples-jar-with-dependencies.jar     createdatabase test-instance example-db
Feb 11, 2020 11:45:15 AM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<17>: (spanner.googleapis.com:443)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:93)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:64)
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:357)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:455)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:101)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:130)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:459)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:241)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1.start(CensusTracingModule.java:392)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1.start(CensusStatsModule.java:694)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor$1.start(GrpcHeaderInterceptor.java:95)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1.start(SpannerErrorInterceptor.java:67)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor$HeaderAttachingClientCall.start(MetadataUtils.java:88)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:308)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:280)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:189)
	at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:86)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.api.gax.grpc.GrpcOperationSnapshotCallable.futureCall(GrpcOperationSnapshotCallable.java:58)
	at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
	at com.google.api.gax.tracing.TracedOperationInitialCallable.futureCall(TracedOperationInitialCallable.java:61)
	at com.google.api.gax.rpc.OperationCallableImpl.futureCall(OperationCallableImpl.java:82)
	at com.google.api.gax.tracing.TracedOperationCallable.futureCall(TracedOperationCallable.java:78)
	at com.google.api.gax.rpc.OperationCallable$1.futureCall(OperationCallable.java:150)
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.createDatabase(GapicSpannerRpc.java:378)
	at com.google.cloud.spanner.SpannerImpl$DatabaseAdminClientImpl.createDatabase(SpannerImpl.java:462)
	at com.example.spanner.SpannerSample.createDatabase(SpannerSample.java:197)
	at com.example.spanner.SpannerSample.run(SpannerSample.java:1443)
	at com.example.spanner.SpannerSample.main(SpannerSample.java:1680)
```

I see [similar issues](https://github.com/googleapis/google-cloud-java/issues/4700) that were filed for other products. The root cause alluded to in the earlier reports is that you can run into this if you're using the Maven shade plugin but I'm using the `pom.xml` provided in a fresh clone of the repository (at commit [36af56](https://github.com/GoogleCloudPlatform/java-docs-samples/commit/36af560b0bb7e65995e7d67e3a1edc9b547cf61a)).

**Comment by skuruppu** [comment]
@antfitch also ran into the same issue.

**Comment by olavloite** [comment]
@skuruppu I'll have a look right away. The samples do seem to use the Maven shade plugin in the build process, so it is probably a similar issue as in https://github.com/googleapis/google-cloud-java/issues/4700.
