### ISSUE TITLE
Upgrade Spanner samples to OpenCensus 0.25.0

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2233]
## In which file did you encounter the issue?
spanner/cloud-client/pom.xml

### Did you change the file? If so, how?
Upgrade OpenCensus to v0.25.0 by RenovateBot in #2224 

## Describe the issue

There are two issues here, both w/ the Spanner Samples:
SpannerSampleIT
```
java.lang.IllegalAccessError: tried to access field io.opencensus.trace.unsafe.ContextUtils.CONTEXT_SPAN_KEY from class io.grpc.internal.CensusTracingModule$TracingClientInterceptor
	at com.example.spanner.SpannerSampleIT.setUp(SpannerSampleIT.java:61)
```
QuickStartSampleIT
```
com.google.cloud.spanner.SpannerException: UNKNOWN: tried to access field io.opencensus.trace.unsafe.ContextUtils.CONTEXT_SPAN_KEY from class io.grpc.internal.CensusTracingModule$TracingClientInterceptor
	at com.example.spanner.QuickstartSampleIT.testQuickstart(QuickstartSampleIT.java:58)
Caused by: com.google.cloud.spanner.SpannerException: UNKNOWN: tried to access field io.opencensus.trace.unsafe.ContextUtils.CONTEXT_SPAN_KEY from class io.grpc.internal.CensusTracingModule$TracingClientInterceptor
Caused by: java.lang.IllegalAccessError: tried to access field io.opencensus.trace.unsafe.ContextUtils.CONTEXT_SPAN_KEY from class io.grpc.internal.CensusTracingModule$TracingClientInterceptor
```

**Comment by skuruppu** [comment]
I can reproduce the issue with both OpenCensus version 0.24.0 and 0.25.0. Did a quick search to see if other people have run into this issue. Not much help there. I found https://github.com/census-instrumentation/opencensus-java/issues/2004 but it's still open.

@mayurkale22 would you be able to give some pointers on how to fix this?

**Comment by mayurkale22** [comment]
This is related to https://github.com/census-instrumentation/opencensus-java/pull/1938

I think we should use the latest version of `grpc` dependency. To solve the issue, I have added `grpc-netty-shaded` and `grpc-core` into the exclusion list and separately addded latest version of `grpc-netty-shaded:1.21.0`.

```
<dependency>
      <!-- Version auto-managed by BOM -->
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-spanner</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava-jdk5</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.opencensus</groupId>
          <artifactId>opencensus-api</artifactId>
        </exclusion>
        <!-- START OF NEW CODE -->
        <exclusion>
          <groupId>io.grpc</groupId>
          <artifactId>grpc-netty-shaded</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.grpc</groupId>
          <artifactId>grpc-core</artifactId>
        </exclusion>
       <!-- END OF NEW CODE -->
      </exclusions>
    </dependency>
```
