### ISSUE TITLE
healthcare/v1beta1 test_Hl7v2MessageList failed

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#2491]
Test failed with BOM update PR #2484 
[Test Fusion](https://fusion.corp.google.com/runanalysis/buildlogs/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/KOKORO/9acde03e-5a5d-4af6-b333-1c14faee35d1/0/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/Targets)

**Comment by lesv** [comment]
```
- testing healthcare/v1beta1
------------------------------------------------------------
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.853 s <<< FAILURE! - in snippets.healthcare.Hl7v2MessageTests
[ERROR] test_Hl7v2MessageList(snippets.healthcare.Hl7v2MessageTests)  Time elapsed: 0.507 s  <<< ERROR!
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at snippets.healthcare.hl7v2.messages.HL7v2MessageList.hl7v2MessageList(HL7v2MessageList.java:67)
	at snippets.healthcare.Hl7v2MessageTests.test_Hl7v2MessageList(Hl7v2MessageTests.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by lesv** [comment]
I commited #2484 which added this issue.

**Comment by lesv** [comment]
Stuff also shows up in PR #2384 Java 11 testing:
```
------------------------------------------------------------
- testing healthcare/v1beta1
------------------------------------------------------------
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.923 s <<< FAILURE! - in snippets.healthcare.Hl7v2MessageTests
[ERROR] test_Hl7v2MessageList(snippets.healthcare.Hl7v2MessageTests)  Time elapsed: 0.459 s  <<< ERROR!
java.lang.NullPointerException
	at java.base/java.util.ArrayList.addAll(ArrayList.java:701)
	at snippets.healthcare.hl7v2.messages.HL7v2MessageList.hl7v2MessageList(HL7v2MessageList.java:67)
	at snippets.healthcare.Hl7v2MessageTests.test_Hl7v2MessageList(Hl7v2MessageTests.java:140)
```

**Comment by lesv** [comment]
Closing PR #2396 due to this.
```
------------------------------------------------------------
- testing healthcare/v1beta1
------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/healthcare/v1beta1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java:[67,31] cannot find symbol
  symbol:   method getMessages()
  location: variable response of type com.google.api.services.healthcare.v1beta1.model.ListMessagesResponse
```

**Comment by lesv** [comment]
Similar issues in PR #2456

**Comment by lesv** [comment]
Please make sure to upgrade com.google.cloud.samples:shared-configuration to v1.0.14 and fix any issues.

**Comment by lesv** [comment]
Please fix or remove the sample before 4/12.

**Comment by dzlier-gcp** [comment]
This test seems to succeed after #2456. Closing until it fails again.
