### ISSUE TITLE
video/beta testSpeechTranscription failed

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/java-docs-samples#2492]
Test failed with BOM update PR #2484 
[Test Fusion](https://fusion.corp.google.com/runanalysis/buildlogs/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/KOKORO/9acde03e-5a5d-4af6-b333-1c14faee35d1/0/prod%3Acloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava8%2Fpresubmit/Targets)

**Comment by munkhuushmgl** [comment]
Due to access issue, I cant see output from `Test Fusion`.

Which sample is it associated with?

**Comment by averikitsch** [comment]
Looks like flaky request limit
```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 189.048 s <<< FAILURE! - in com.example.video.DetectIT
[ERROR] testSpeechTranscription(com.example.video.DetectIT)  Time elapsed: 0.38 s  <<< ERROR!
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:779844219229'.
	at com.example.video.DetectIT.testSpeechTranscription(DetectIT.java:64)
Caused by: com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:779844219229'.
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:779844219229'.

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.772 s <<< FAILURE! - in com.example.video.DetectPersonIT
[ERROR] testDetectPerson(com.example.video.DetectPersonIT)  Time elapsed: 1.772 s  <<< ERROR!
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:779844219229'.
	at com.example.video.DetectPersonIT.testDetectPerson(DetectPersonIT.java:47)
Caused by: com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:779844219229'.
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'videointelligence.googleapis.com' for consumer 'project_number:779844219229'.

[ERROR] Errors: 
[ERROR]   DetectIT.testSpeechTranscription:64 » Execution com.google.api.gax.rpc.Resourc...
[ERROR]   DetectPersonIT.testDetectPerson:47 » Execution com.google.api.gax.rpc.Resource...
[ERROR] Tests run: 15, Failures: 0, Errors: 2, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M3:verify (default) on project video-google-cloud-samples-beta: There are test failures.
[ERROR] 
[ERROR] Please refer to /tmpfs/src/github/java-docs-samples/video/beta/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
I am going to close since it passed now.
