### ISSUE TITLE
SecurityCenter: ALREADY_EXISTS: Requested entity already exists

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#2573]
securityCenter/
`NotificationConfigSnippetTests(sponge_log).testListNotificationConfig`
```
com.google.api.gax.rpc.AlreadyExistsException: io.grpc.StatusRuntimeException: ALREADY_EXISTS: Requested entity already exists
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:53)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure
```
Found in PR #2563 

Note: Something is amiss in how this things is created and cleaned up.  Please use UUID's and please clean up so we don't have things growing.  Also, ask for access to the test project so we can clean up.

**Comment by averikitsch** [comment]
@tdh911 PTAL
