### ISSUE TITLE
Billing Issue in Google Clould Platform 

### ISSUE THREAD

**Issue by Gopu619** [GoogleCloudPlatform/java-docs-samples#276]
I have created a new project and enabled the billing. But I Still got the billing error( Billing has disabled) .
Please help us to resolve the issue.

**Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Project charming-module-137923 (#808448574146) has billing disabled. Please enable it.",
    "reason" : "forbidden"
  } ],
  "message" : "Project charming-module-137923 (#808448574146) has billing disabled. Please enable it.",
  "status" : "PERMISSION_DENIED"
}

at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
at com.google.cloud.language.samples.Analyze.analyzeEntities(Analyze.java:178)
at com.google.cloud.language.samples.Analyze.main(Analyze.java:78)**

**Comment by tswast** [comment]
Hi @Gopu619, thanks for reporting this issue.

Are you still encountering it? It can take a few minutes for billing information to propagate after enabling it.

Does the project ID you are seeing match the project you enabled billing for? Perhaps the wrong Google Application Default Credentials are being used if they do not match up. Which sample are you trying to run?

**Comment by Gopu619** [comment]
Hi **@tswast**, I am trying to run below sample project.
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/language/analysis

**Comment by elibixby** [comment]
@Gopu619 Even if the project has a billing account attached, if that billing account is closed the project will count as having billing disabled. 

Try running the following:

```
gcloud components install alpha
gcloud alpha billing projects describe charming-module-137923
```

Or checking in the console to make the billing account you are using hasn't been closed. (e.g. by the free trial ending).

**Comment by puneith** [comment]
@Gopu619 Were you able to get this working?

**Comment by puneith** [comment]
@Gopu619 We are closing this issue due to inactivity. Please, feel free to re-open if its still unresolved at your end.
