### ISSUE TITLE
Connecting to a secured websocket

### ISSUE THREAD

**Issue by Haimonti** [GoogleCloudPlatform/java-docs-samples#3085]
I'm trying to connect to a secured websocket using Jetty. 
My client looks like this:

===========
package interContILP;
import java.io.*;
import java.nio.file.Path;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.net.URI;
import java.util.concurrent.Future;
import java.nio.ByteBuffer;
import java.util.concurrent.TimeUnit;
import org.eclipse.jetty.websocket.api.Session;
import java.util.concurrent.Executors;

import java.util.concurrent.Executors;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.X509ExtendedTrustManager;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.client.HttpClient;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.server.handler.ContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.eclipse.jetty.server.HttpConnectionFactory;
import org.eclipse.jetty.util.thread.QueuedThreadPool;
import org.eclipse.jetty.websocket.client.WebSocketClient;
import org.eclipse.jetty.util.ssl.SslContextFactory;

public class MainClient
{
    public static void main(String[] args) throws Exception
    {
    	**SslContextFactory sslContextFactory = new SslContextFactory();**
         sslContextFactory.setTrustAll(true);
    	
         **HttpClient httpClient = new HttpClient(sslContextFactory);**

        URI uri = URI.create("ws://172.16.1.100:8443/interContILP_WithMaven/");
        WebSocketClient client = new WebSocketClient();
        try
        {
        		long start_time=System.nanoTime();
        		httpClient.start();
                         client.start();
                System.out.println("--------------------------------------------------------------");
               System.out.println(httpClient.dump());
                System.out.println("--------------------------------------------------------------");

                // The socket that receives events
                ClientSocket socket = new ClientSocket();
                // Attempt Connect
                Future<Session> fut = client.connect(socket,uri);
                // Wait for Connect
                Session session = fut.get();
                long end_time=System.nanoTime();
                long connTime = end_time - start_time;
                System.out.println("Connection time (ms) is ... "+connTime/1000000);
               }
             catch(Exception e)

            // AND SOME MORE FUNCTIONALITY FROM THE APPLICATION
====
The above throws the following exception: 
java.util.concurrent.ExecutionException: org.eclipse.jetty.websocket.api.UpgradeException: 200 OK
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at interContILP.MainClient.main(MainClient.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:290)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: 200 OK
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:520)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:459)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:405)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:298)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:606)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1534)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1382)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:171)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:132)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:137)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	... 1 more

The connection to the websocket server seems to be an issue. It works with localhost, but when executed in a remote client/server setting it does not and throws the upgrade exception.

Any suggesttions?

**Comment by lesv** [comment]
Q seems abandoned.  Feel free to reopen if you still wish help.
