### ISSUE TITLE
helloworld-new-plugins doesn't even work

### ISSUE THREAD

**Issue by andrewzhaosc** [GoogleCloudPlatform/java-docs-samples#332]
:compileJava
:processResources UP-TO-DATE
:classes
:war
:explodeWar
:assemble
:appengineRun
Traceback (most recent call last):
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 84, in <module>
    _run_file(__file__, globals())
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 80, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1040, in <module>
    main()
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in main
    dev_server.start(options)
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 758, in start
    options.config_paths, options.app_id)
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 813, in __init__
    config_paths = self._config_files_from_paths(config_paths)
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 879, in _config_files_from_paths
    self._config_files_from_dir(path) if os.path.isdir(path) else [path])
  File "/Users/andrew.zhao/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 910, in _config_files_from_dir
    (dir_path, or_web_inf))
google.appengine.tools.devappserver2.errors.AppConfigNotFoundError: "/Users/andrew.zhao/java-docs-samples/appengine/helloworld-new-plugins/build/exploded-app" is a directory but does not contain app.yaml or app.yml
:appengineRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':appengineRun'.
> Non zero exit: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.752 secs

**Comment by lesv** [comment]
Hi Andrew,

Thanks for your report.

Could you try this again and then email me `lesv@google.com` the following results of:

1. `gcloud info`
2. The last log file mentioned at the bottom of `gcloud info`
3. `gcloud componets list`
4. A copy of your path

What I'm looking for is, `app-engine-java` extensions are installed, and an old AppEngine Java SDK isn't on your path.  If you happen to notice these things, and fix it, and it works, could you let us know?

Thanks -- Les

**Comment by lesv** [comment]
@GoogleCloudPlatform/cloud-tools-for-java FYI

**Comment by andrewzhaosc** [comment]
Hmm it seems like I somehow didn't have the java extensions installed, which is strange because I could maven deploy with no issues.

I guess this can be closed

**Comment by patflynn** [comment]
@meltsufin
@loosebazooka
@elharo
@etanshaul

It seems like this is a bug for our tools in terms of the error message that users of the plugins are getting when the app-engine-java extensions are missing.

**Comment by elharo** [comment]
Yes, we've seen this in Eclipse too including just hours ago with @YnR 
https://github.com/GoogleCloudPlatform/cloud-tools-for-eclipse/issues/668

We need to make sure we have good detection and messaging around this situation. It's an argument for installing our own bundled cloud SDK.

**Comment by etanshaul** [comment]
We do have this to track the issue:

https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/165

**Comment by meltsufin** [comment]
Tracking for Maven as well: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/80
