### ISSUE TITLE
Bigtable updates from RenovateBot are incompatible...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#3397]
PR #3379 #3380 #3396 are not merging for some reason, could someone involved with SoDA please take a look.

**Comment by lesv** [comment]
#3396 managed to merge, but @shubha-rajan thinks it may be a timing issue, so we should fix that.

# Java 11
```
------------------------------------------------------------
- testing bigtable
------------------------------------------------------------
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.232 s <<< FAILURE! - in com.m.examples.bigtable.InstanceAdminExampleTest
[ERROR] com.m.examples.bigtable.InstanceAdminExampleTest.testCreateAndDeleteInstance  Time elapsed: 7.195 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.m.examples.bigtable.InstanceAdminExampleTest.testCreateAndDeleteInstance(InstanceAdminExampleTest.java:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

**Comment by lesv** [comment]
#3379 & #3380 appear fixed as well.  Downgrading to p2

**Comment by billyjacobson** [comment]
This was just marked as flakey, I'm not sure how to fix it. I ran it in a loop, but it continued to work until I ran out of instances I'm allowed to create per day @lesv Is there a way I can get more information to be logged from this error message?

**Comment by lesv** [comment]
If you go into the PR, you can find the link to sponge and look at it.  I've been trying to get folks to switch from throwing `IOException` to the real more detailed exceptions that actually give some useful info.  In this case, it's an assert, so that's not going to help.

**Comment by shubha-rajan** [comment]
Can we modify the tests to capture StdOut and use `assertThat` to verify that there's a success message printed out? That way if the assertion is false it'll print the diff. I've seen other tests do that.

**Comment by lesv** [comment]
@shubha-rajan That's how most tests work, though we found that many tests don't restore stdout so it's rarely actually printed.  Note - just calling `System.setOut(null);` doesn't work.

What I'd like to do in GoogleCloudPlatform/java-repo-tools#161 is enable the ability to grab stdout for each test and upload it to sponge or it's like.

**Comment by lesv** [comment]
@shubha-rajan I think this has been fixed for many projects.  Can we close this, or is it still an issue?
