### ISSUE TITLE
The Cloud Firestore API is not available for Cloud Datastore projects.

### ISSUE THREAD

**Issue by NoahDragon** [GoogleCloudPlatform/java-docs-samples#3436]
## In which file did you encounter the issue?

`java-docs-samples/firestore/`

Followed the instruction of how to run the sample code.

### Did you change the file? If so, how?

No

## Describe the issue

I have created a project with the firestore native mode. I can write/read data from the Cloud Console, so I could confirm the project has Cloud Firestore.
![image](https://user-images.githubusercontent.com/5704064/88854841-f0f88900-d1bf-11ea-9884-c98b6bb97fda.png)

Full error log:
```
########## Adding document 1 ##########
Exception in thread "main" java.util.concurrent.ExecutionException: com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: The Cloud Firestore API is not available for Cloud Datastore projects.
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:545)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:86)
        at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
        at com.example.firestore.Quickstart.addDocument(Quickstart.java:87)
        at com.example.firestore.Quickstart.run(Quickstart.java:168)
        at com.example.firestore.Quickstart.main(Quickstart.java:197)
Caused by: com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: The Cloud Firestore API is not available for Cloud Datastore projects.
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:59)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
        at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
        at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1050)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1176)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:760)
        at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:545)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: The Cloud Firestore API is not available for Cloud Datastore projects.
        at io.grpc.Status.asRuntimeException(Status.java:533)
        ... 15 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by lesv** [comment]
@NoahDragon I've asked @BenWhitehead to reply, but the quick answer is that you can either have Firestore or Datastore, but not both.

I think there is some nuance on when the project was created, but I don't know it, so I'll leave the rest to Ben.

**Comment by lesv** [comment]
A couple of docs that might interest you:
* [Choosing between Native mode and Datastore mode](https://cloud.google.com/datastore/docs/firestore-or-datastore)
* [Automatic Upgrade to Firestore](https://cloud.google.com/datastore/docs/upgrade-to-firestore)

**Comment by NoahDragon** [comment]
Thank you, @lesv 

I understand that only one mode of firestore could be chosen under the GCP project, and I have intended set it to the native mode. When I clicked the datastore in the cloud console, it shows the following:

![image](https://user-images.githubusercontent.com/5704064/88867865-a9ccc100-d1dc-11ea-8386-ea941adbffd6.png)

So I assume the project has set to the Firestore native mode correct.

**Comment by lesv** [comment]
Again, I'm not an expert on Firestore, but yes, it appears to be.

**Comment by lesv** [comment]
You might wish to contact support rather than waiting for @BenWhitehead to answer.

**Comment by BenWhitehead** [comment]
@NoahDragon And I are chatting offline about this, will update here when we have a resolution.

**Comment by NoahDragon** [comment]
Thanks @lesv and @BenWhitehead for the quick response and help. There is a misconfiguration in my cloud machine, but not sure why the code pick it up instead of setting in my service key. Ben is digging into the code to check. Close this ticket as it specific to certain type of cloud machines.
