### ISSUE TITLE
error when using iot/api-client/end-to-end-example/src/main/java/com/example/cloud/iot/endtoend/CloudiotPubsubExampleServer.java  on Java Spring Boot

### ISSUE THREAD

**Issue by tranthanhtung04101995** [GoogleCloudPlatform/java-docs-samples#3850]
` java.lang.IllegalStateException: Expected the service InnerService [FAILED] to be RUNNING, but the service has FAILED
Exception in thread "main" java.lang.IllegalStateException: Expected the service InnerService [FAILED] to be TERMINATED, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
	at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:329)
	at com.google.api.core.AbstractApiService.awaitTerminated(AbstractApiService.java:104)
	at com.vnnet.iot.web.endtoend.CloudiotPubsubExampleServer.run(CloudiotPubsubExampleServer.java:313)
	at com.vnnet.iot.web.endtoend.CloudiotPubsubExampleServer.main(CloudiotPubsubExampleServer.java:328)
Caused by: java.lang.IllegalStateException: Expected the service InnerService [FAILED] to be RUNNING, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
	at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:302)
	at com.google.api.core.AbstractApiService.awaitRunning(AbstractApiService.java:96)
	at com.google.cloud.pubsub.v1.Subscriber.startConnections(Subscriber.java:379)
	at com.google.cloud.pubsub.v1.Subscriber.startStreamingConnections(Subscriber.java:340)
	at com.google.cloud.pubsub.v1.Subscriber.access$1300(Subscriber.java:93)
	at com.google.cloud.pubsub.v1.Subscriber$2.run(Subscriber.java:288)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by munkhuushmgl** [comment]
@tranthanhtung04101995 Could you provide your code snippet used to output this error?

**Comment by lesv** [comment]
@tranthanhtung04101995 I'm going to close because this is a stale issue - feel free to provide the requested info and reopen.
