### ISSUE TITLE
storage/json-api tests are brittle

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#4194]
Found in #4149 

Looking at storage/json-api/src/test/java/StorageSampleTest.java it appears that `testUploadDelete()` doesn't wait for GCS eventual consistency.

```
------------------------------------------------------------
- testing storage/json-api
------------------------------------------------------------
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.692 s <<< FAILURE! - in StorageSampleTest
[ERROR] StorageSampleTest.testUploadDelete  Time elapsed: 2.325 s  <<< ERROR!
com.google.api.client.googleapis.json.GoogleJsonResponseException:
404 Not Found
DELETE https://storage.googleapis.com/storage/v1/b/java-docs-samples-testing/o/storage-sample-test-upload.txt
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "No such object: java-docs-samples-testing/storage-sample-test-upload.txt",
    "reason" : "notFound"
  } ],
  "message" : "No such object: java-docs-samples-testing/storage-sample-test-upload.txt"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:149)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:112)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:39)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
```

**Comment by lesv** [comment]
It also should include a UUID in the path as several of these tests will likely run at the same time.  The same PR run's at least two languages.

**Comment by JesseLovelace** [comment]
Are these sample published on any docs pages?

**Comment by lesv** [comment]
I have no idea, but will try searching

**Comment by lesv** [comment]
I can't find them through codesearch

**Comment by lesv** [comment]
@frankyn @JesseLovelace If you can confirm that they shouldn't exist, I'm happy to remove them.

**Comment by lesv** [comment]
ping

**Comment by frankyn** [comment]
Hi @lesv,

I did a search over this directory and it's not currently used in cloud documentation. Let's remove these samples because this isn't the way we want users to use the Storage API in Java additionally it's not surfaced in cloud documentation.
