### ISSUE TITLE
iam/iam-client flaky test

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#4370]
Found in #4365 in Java 11, not Java 8.  Running again, it doesn't fail.
```
------------------------------------------------------------
- testing iam/api-client
------------------------------------------------------------
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.554 s <<< FAILURE! - in iam.snippets.QuickstartTests
[ERROR] iam.snippets.QuickstartTests.testQuickstart  Time elapsed: 3.43 s  <<< ERROR!
java.lang.NullPointerException
	at iam.snippets.QuickstartTests.testQuickstart(QuickstartTests.java:138)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by lesv** [comment]
The problem appears to be `binding` is null.  Probably related to multiple tests running at the same time. (java 8 & java 11)

**Comment by lesv** [comment]
Fixed.
