### ISSUE TITLE
Java 8 trace failing - it's possible all that's needed is to make sure the class gets loaded.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#5012]
Found in #4981 

------------------------------------------------------------
- testing trace
------------------------------------------------------------
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.332 s <<< FAILURE! - in com.example.trace.TraceSampleIT
[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegisterGoogleCloudPlatform  Time elapsed: 0.221 s  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory
	at com.example.trace.TraceSampleIT.testCreateAndRegisterGoogleCloudPlatform(TraceSampleIT.java:59)
Caused by: java.lang.ClassNotFoundException: com.google.api.client.json.jackson2.JacksonFactory
	at com.example.trace.TraceSampleIT.testCreateAndRegisterGoogleCloudPlatform(TraceSampleIT.java:59)

[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegisterGoogleCloudPlatform  Time elapsed: 0.223 s  <<< ERROR!
java.lang.IllegalStateException: Stackdriver exporter is not registered.
	at com.example.trace.TraceSampleIT.tearDown(TraceSampleIT.java:42)

[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegister  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.opencensus.exporter.trace.stackdriver.StackdriverTraceConfiguration
	at com.example.trace.TraceSampleIT.testCreateAndRegister(TraceSampleIT.java:47)

[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegister  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Stackdriver exporter is not registered.
	at com.example.trace.TraceSampleIT.tearDown(TraceSampleIT.java:42)

[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegisterFullSampled  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.opencensus.exporter.trace.stackdriver.StackdriverTraceConfiguration
	at com.example.trace.TraceSampleIT.testCreateAndRegisterFullSampled(TraceSampleIT.java:53)

[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegisterFullSampled  Time elapsed: 0.003 s  <<< ERROR!
java.lang.IllegalStateException: Stackdriver exporter is not registered.
	at com.example.trace.TraceSampleIT.tearDown(TraceSampleIT.java:42)

[ERROR] Errors:
[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegister
[ERROR]   Run 1: TraceSampleIT.testCreateAndRegister:47 » NoClassDefFound Could not initialize ...
[ERROR]   Run 2: TraceSampleIT.tearDown:42 » IllegalState Stackdriver exporter is not registere...
[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegisterFullSampled
[ERROR]   Run 1: TraceSampleIT.testCreateAndRegisterFullSampled:53 » NoClassDefFound Could not ...
[ERROR]   Run 2: TraceSampleIT.tearDown:42 » IllegalState Stackdriver exporter is not registere...
[ERROR] com.example.trace.TraceSampleIT.testCreateAndRegisterGoogleCloudPlatform
[ERROR]   Run 1: TraceSampleIT.testCreateAndRegisterGoogleCloudPlatform:59 » NoClassDefFound co...
[ERROR]   Run 2: TraceSampleIT.tearDown:42 » IllegalState Stackdriver exporter is not registere...
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

**Comment by lesv** [comment]
Duplicate of #5020 #5021 #5022
