### ISSUE TITLE
grpc 1.2.0 having issues with netty

### ISSUE THREAD

**Issue by chrisgarry** [GoogleCloudPlatform/java-docs-samples#579]
```
userpc:grpc username$ bin/speech-sample-async.sh --host=speech.googleapis.com --port=443 \
> --uri=resources/audio.raw --sampling=16000
Exception in thread "main" java.lang.NoSuchMethodError: io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize()I
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:274)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:239)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:69)
	at com.examples.cloud.speech.AsyncRecognizeClient.createChannel(AsyncRecognizeClient.java:90)
	at com.examples.cloud.speech.AsyncRecognizeClient.main(AsyncRecognizeClient.java:229)
```

## In which file did you encounter the issue?

```
git/java-docs-samples/speech/grpc/pom.xml
```

### Did you change the file? If so, how?

```
userpc:grpc username$ git diff
diff --git a/speech/grpc/pom.xml b/speech/grpc/pom.xml
index 21b508a..70c1507 100644
--- a/speech/grpc/pom.xml
+++ b/speech/grpc/pom.xml
@@ -49,7 +49,7 @@ limitations under the License.
   <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <codehaus-versions-maven-plugin-version>2.3</codehaus-versions-maven-plugin-version>
-    <grpc-version>1.2.0</grpc-version> <!-- 1.1.2 doesn't work - DO NOT UPGRADE -->
+    <grpc-version>1.0.3</grpc-version> <!-- 1.1.2 doesn't work - DO NOT UPGRADE -->
     <maven-compiler-plugin-version>3.6.0</maven-compiler-plugin-version>
     <xolstice-protobuf-maven-plugin-version>0.5.0</xolstice-protobuf-maven-plugin-version>
```

## Describe the issue

There are issues finding Netty in the latest grpc version bump.

**Comment by lesv** [comment]
I've rolled back to 1.0.3 for now.

**Comment by lesv** [comment]
@chrisgarry Is this still a problem for you?

**Comment by chrisgarry** [comment]
@lesv nope my local version change resolved it. I haven't pulled in any recent changes to verify if you guys resolved.

**Comment by atejandro** [comment]
I have the same problem in a project I'm working on. This time however, it happens when I change from version 1.2.0 to version 1.3.0.

`org.jini.rio.core.JSBInstantiationException: java.lang.NoSuchMethodError: io.grpc.netty.NettyChannelBuilder.maxInboundMessageSize()I
        at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:333)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:239)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:69)
        at com.pagosonline.maf.channel.GrpcManagedChannel.<init>(GrpcManagedChannel.java:32)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
        at org.springframework.beans.factory.support.ConstructorResolver$1.run(ConstructorResolver.java:274)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:272)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)`

Is rolling back to 1.2.0 the only solution? Are you still having the same problem with this new release?

**Comment by chrisgarry** [comment]
@atejandro This is the second version bump of GRPC that has had this issue. I wonder if the same change that broke this last time was reintroduced, or it wasn't patched in a sustainable way. I am no longer using this so I'm not sure. Good luck!

**Comment by lesv** [comment]
@gguuss PTAL

**Comment by gguuss** [comment]
I just was looking at the java/speech samples for forever trying to figure this out. I believe we removed the GRPC samples in favor of those using Cloud Client libraries. Can you point me to the code you're running?

Do [the samples in this folder](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/speech/cloud-client) resolve your issue?  I cannot reproduce the issue.

**Comment by lesv** [comment]
If you are still having issues look at:
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/TROUBLESHOOTING.md
Should be obsolete.
