### ISSUE TITLE
SA can no longer change IAM settings for individual resources or at project level

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/java-docs-samples#6571]
Found in #6462 
# Java 8 - SA can no longer change IAM settings for individual resources or at the project level.  (Due to LatchKey)

```
#
# iam/api-client
#

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.7 s <<< FAILURE! - in iam.snippets.QuickstartTests
[ERROR] iam.snippets.QuickstartTests.testQuickstart  Time elapsed: 1.66 s  <<< ERROR!
java.lang.NullPointerException
	at iam.snippets.Quickstart.setPolicy(Quickstart.java:170)
	at iam.snippets.Quickstart.addBinding(Quickstart.java:122)
	at iam.snippets.QuickstartTests.testQuickstart(QuickstartTests.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

[ERROR] Errors:
[ERROR]   QuickstartTests.testQuickstart:126 » NullPointer
[ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0

#
# iot/api-client/manager
#

[ERROR] Tests run: 21, Failures: 0, Errors: 2, Skipped: 4, Time elapsed: 1,036.891 s <<< FAILURE! - in com.example.cloud.iot.examples.ManagerIT
[ERROR] com.example.cloud.iot.examples.ManagerIT.testSetIam  Time elapsed: 37.508 s  <<< ERROR!
com.google.api.client.googleapis.json.GoogleJsonResponseException:
403 Forbidden
POST https://cloudiot.googleapis.com/v1/projects/java-docs-samples-testing/locations/us-central1/registries/java-reg-a04914c1-6-1639071882545:setIamPolicy
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "The caller does not have permission",
    "reason" : "forbidden"
  } ],
  "message" : "The caller does not have permission",
  "status" : "PERMISSION_DENIED"
}
	at com.example.cloud.iot.examples.ManagerIT.testSetIam(ManagerIT.java:334)

[ERROR] com.example.cloud.iot.examples.ManagerIT.testPatchRsa  Time elapsed: 0.406 s  <<< ERROR!
com.google.api.gax.rpc.AlreadyExistsException: io.grpc.StatusRuntimeException: ALREADY_EXISTS: Resource already exists in the project (resource=java-pst-c7fd7135-4-1639071882545).
Caused by: io.grpc.StatusRuntimeException: ALREADY_EXISTS: Resource already exists in the project (resource=java-pst-c7fd7135-4-1639071882545).

[ERROR] Errors:
[ERROR]   ManagerIT.testPatchRsa » AlreadyExists io.grpc.StatusRuntimeException: ALREADY...
[ERROR]   ManagerIT.testSetIam:334 » GoogleJsonResponse 403 Forbidden
POST https://cloud...
[ERROR] Tests run: 21, Failures: 0, Errors: 2, Skipped: 4

#
# kms
#

[ERROR] Tests run: 29, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 50.743 s <<< FAILURE! - in kms.SnippetsIT
[ERROR] kms.SnippetsIT.testGetPublicKey  Time elapsed: 0.674 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1ae1bb91-a8cc-45ca-a992-078e8f636410/cryptoKeyVersions/1' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1ae1bb91-a8cc-45ca-a992-078e8f636410/cryptoKeyVersions/1' (or it may not exist).

[ERROR] kms.SnippetsIT.testDecryptAsymmetric  Time elapsed: 0.559 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1ae1bb91-a8cc-45ca-a992-078e8f636410/cryptoKeyVersions/1' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1ae1bb91-a8cc-45ca-a992-078e8f636410/cryptoKeyVersions/1' (or it may not exist).

[ERROR] kms.SnippetsIT.testSignAsymmetric  Time elapsed: 0.573 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToSign' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1211c86d-02d6-40a3-afca-784091702b89' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToSign' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1211c86d-02d6-40a3-afca-784091702b89' (or it may not exist).

[ERROR] kms.SnippetsIT.testEncryptAsymmetric  Time elapsed: 0.575 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1ae1bb91-a8cc-45ca-a992-078e8f636410/cryptoKeyVersions/1' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1ae1bb91-a8cc-45ca-a992-078e8f636410/cryptoKeyVersions/1' (or it may not exist).

[ERROR] kms.SnippetsIT.testVerifyAsymmetricRsa  Time elapsed: 0.56 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToSign' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1211c86d-02d6-40a3-afca-784091702b89' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToSign' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/1211c86d-02d6-40a3-afca-784091702b89' (or it may not exist).

[ERROR] kms.SnippetsIT.testVerifyAsymmetricEc  Time elapsed: 0.59 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToSign' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/bbd7fadd-e19b-4384-9513-602637df1139' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToSign' denied on resource 'projects/java-docs-samples-testing/locations/us-east1/keyRings/afdc4f2d-1946-4f4e-a556-f2ac6be8e3a7/cryptoKeys/bbd7fadd-e19b-4384-9513-602637df1139' (or it may not exist).

[ERROR] Errors:
[ERROR]   SnippetsIT.testDecryptAsymmetric » PermissionDenied io.grpc.StatusRuntimeExcep...
[ERROR]   SnippetsIT.testEncryptAsymmetric » PermissionDenied io.grpc.StatusRuntimeExcep...
[ERROR]   SnippetsIT.testGetPublicKey » PermissionDenied io.grpc.StatusRuntimeException:...
[ERROR]   SnippetsIT.testSignAsymmetric » PermissionDenied io.grpc.StatusRuntimeExceptio...
[ERROR]   SnippetsIT.testVerifyAsymmetricEc » PermissionDenied io.grpc.StatusRuntimeExce...
[ERROR]   SnippetsIT.testVerifyAsymmetricRsa » PermissionDenied io.grpc.StatusRuntimeExc...
[ERROR] Tests run: 29, Failures: 0, Errors: 6, Skipped: 0

#
# secretmanager
#

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.1 s <<< FAILURE! - in secretmanager.QuickstartIT
[ERROR] secretmanager.QuickstartIT.quickstart_test  Time elapsed: 5.829 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.versions.access' denied for resource 'projects/779844219229/secrets/java-quickstart-04e07294-bbc4-45c4-bd6c-532990da0d3a/versions/1' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.versions.access' denied for resource 'projects/779844219229/secrets/java-quickstart-04e07294-bbc4-45c4-bd6c-532990da0d3a/versions/1' (or it may not exist).

[ERROR] Tests run: 20, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 13.798 s <<< FAILURE! - in secretmanager.SnippetsIT
[ERROR] secretmanager.SnippetsIT.testIamRevokeAccess  Time elapsed: 0.475 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.secrets.setIamPolicy' denied for resource 'projects/779844219229/secrets/java-1639072054467' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.secrets.setIamPolicy' denied for resource 'projects/779844219229/secrets/java-1639072054467' (or it may not exist).

[ERROR] secretmanager.SnippetsIT.testIamGrantAccess  Time elapsed: 0.416 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.secrets.setIamPolicy' denied for resource 'projects/779844219229/secrets/java-1639072054467' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.secrets.setIamPolicy' denied for resource 'projects/779844219229/secrets/java-1639072054467' (or it may not exist).

[ERROR] secretmanager.SnippetsIT.testAccessSecretVersion  Time elapsed: 0.304 s  <<< ERROR!
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.versions.access' denied for resource 'projects/779844219229/secrets/java-1639072055380/versions/1' (or it may not exist).
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'secretmanager.versions.access' denied for resource 'projects/779844219229/secrets/java-1639072055380/versions/1' (or it may not exist).

[ERROR] Errors:
[ERROR]   QuickstartIT.quickstart_test » PermissionDenied io.grpc.StatusRuntimeException...
[ERROR]   SnippetsIT.testAccessSecretVersion » PermissionDenied io.grpc.StatusRuntimeExc...
[ERROR]   SnippetsIT.testIamGrantAccess » PermissionDenied io.grpc.StatusRuntimeExceptio...
[ERROR]   SnippetsIT.testIamRevokeAccess » PermissionDenied io.grpc.StatusRuntimeExcepti...
[ERROR] Tests run: 21, Failures: 0, Errors: 4, Skipped: 0

```

**Comment by lesv** [comment]
I gave a bunch of permissions to our SA's so this is probably no longer an issue.
