### ISSUE TITLE
Opencensus Metric collection example failing with ClassNotFoundException 

### ISSUE THREAD

**Issue by smn-codes** [GoogleCloudPlatform/java-docs-samples#7239]
Quickstart example that is given in the opencensus repo failing with below exception.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory
	at io.opencensus.exporter.stats.stackdriver.StackdriverStatsConfiguration.<clinit>(StackdriverStatsConfiguration.java:50)
	at com.example.opencensus.Quickstart.main(Quickstart.java:26)
Caused by: java.lang.ClassNotFoundException: com.google.api.client.json.jackson2.JacksonFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```

I have just cloned the repo into my machine to ran the example. Did not make changes to either code or pom.xml, still I a getting the aboe exception.

Am I missing something here?

**Comment by lesv** [comment]
@dazuma We probably should deprecate this sample in favor of OpenTelemetry.  Is this in your world or can you send it to someone who should do it?
