### ISSUE TITLE
ApiException in gax.batching.BatchingException

### ISSUE THREAD

**Issue by dwirya** [GoogleCloudPlatform/java-docs-samples#7258]
## In which file did you encounter the issue?

java-docs-samples/bigtable/beam/helloworld/HelloWorldWrite.java

### Did you change the file? If so, how?

No change at all

## Describe the issue

Invocation:
```
mvn compile exec:java -Dexec.mainClass=HelloWorldWrite "-Dexec.args=--project=$PROJECT_ID --bigtableProjectId=$PROJECT_ID --bigtableInstanceId=$INSTANCE_ID --bigtableTableId=$TABLE_ID --runner=dataflow --region=$REGION"
```

Output:
```
Worker configuration: n1-standard-1 in australia-southeast1-a.
Executing operation Create.Values/Read(CreateSource)+ParDo(Anonymous)+CloudBigtableIO.CloudBigtableWriteTransform/ParDo(CloudBigtableSingleTableBufferedWrite)
Starting 1 workers in australia-southeast1-a...
[main] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2022-08-16T23:34:14.018Z: com.google.bigtable.repackaged.com.google.api.gax.batching.BatchingException: Batching finished with 1 batches failed to apply due to: 1 ApiException(1 INTERNAL) and 0 partial failures.
        at com.google.bigtable.repackaged.com.google.api.gax.batching.BatcherImpl.close(BatcherImpl.java:348)
        at com.google.cloud.bigtable.hbase.wrappers.veneer.BulkMutationVeneerApi.close(BulkMutationVeneerApi.java:68)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutatorHelper.close(BigtableBufferedMutatorHelper.java:91)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.close(BigtableBufferedMutator.java:85)
        at com.google.cloud.bigtable.beam.CloudBigtableIO$CloudBigtableSingleTableBufferedWriteFn.finishBundle(CloudBigtableIO.java:818)
Finished operation Create.Values/Read(CreateSource)+ParDo(Anonymous)+CloudBigtableIO.CloudBigtableWriteTransform/ParDo(CloudBigtableSingleTableBufferedWrite)
```

I tried googling this issue, but unfortunately didn't find other people encountering the same problem. The code works fine using DirectRunner, however. Not sure if this is the right place to ask this question, but I'd really appreciate any input for my issue. Thanks in advance!

P.S. I'm using Mac M1, not sure if that'll impact the generated JAR

**Comment by dwirya** [comment]
Closed as it turns out there was a mistake in my service account configuration.
