### ISSUE TITLE
Functions Slack tests failed when upgrading libraries-bom

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/java-docs-samples#7359]
#7355 upgraded the core set of client libraries across many `java-docs-samples` directories, and the build failed on the test below.  This issue has been created to upgrade to the latest `com.google.cloud:libraries-bom` along with any other matching dependencies, and ensure that the test works.

My quick analysis here is:
* The Knowledge Graph library depends on an older 1.3.1 version of `google-api-client`, and 2.0.0 is installed with this upgrade.
* The Knowledge Graph library version in pom.xml is `v1-rev20200809-1.32.1`, but there have not been any new versions [published](https://mvnrepository.com/artifact/com.google.apis/google-api-services-kgsearch) since 2020.
* So, if there is not a way to upgrade the dependencies to make this sample work, we should either remove the sample or remove the dependency on `google-api-services-kgsearch`.

```
[ERROR] Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 3.85 s <<< FAILURE! - in functions.SlackSlashCommandTest
[ERROR] functions.SlackSlashCommandTest.recognizesValidSlackTokenTest  Time elapsed: 3.502 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.google.api.services.kgsearch.v1.Kgsearch$Builder.build(Kgsearch.java:456)
	at functions.SlackSlashCommand.<init>(SlackSlashCommand.java:66)
Caused by: java.lang.IllegalStateException: You are currently running with version 2.0.0 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the Knowledge Graph Search API library.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:534)

[ERROR] functions.SlackSlashCommandTest.handlesSearchErrorTest  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
	at com.google.api.services.kgsearch.v1.Kgsearch$Builder.build(Kgsearch.java:456)
	at functions.SlackSlashCommand.<init>(SlackSlashCommand.java:66)

[ERROR] functions.SlackSlashCommandTest.requiresSlackAuthHeadersTest  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
	at com.google.api.services.kgsearch.v1.Kgsearch$Builder.build(Kgsearch.java:456)

[ERROR] functions.SlackSlashCommandTest.onlyAcceptsPostRequestsTest  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
	at com.google.api.services.kgsearch.v1.Kgsearch$Builder.build(Kgsearch.java:456)
	at functions.SlackSlashCommand.<init>(SlackSlashCommand.java:66)

[ERROR] functions.SlackSlashCommandTest.handlesMultipleUrlParamsTest  Time elapsed: 0.005 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
	at com.google.api.services.kgsearch.v1.Kgsearch$Builder.build(Kgsearch.java:456)

[ERROR] functions.SlackSlashCommandTest.handlesPopulatedKgResultsTest  Time elapsed: 0.011 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
	at com.google.api.services.kgsearch.v1.Kgsearch$Builder.build(Kgsearch.java:456)

[ERROR] functions.SlackSlashCommandTest.handlesEmptyKgResultsTest  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
	at com.google.api.services.kgsearch.v1.Kgsearch$Builder.build(Kgsearch.java:456)

[ERROR] Errors:
[ERROR]   SlackSlashCommandTest.handlesEmptyKgResultsTest:141 » NoClassDefFound Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
[ERROR]   SlackSlashCommandTest.handlesMultipleUrlParamsTest:173 » NoClassDefFound Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
[ERROR]   SlackSlashCommandTest.handlesPopulatedKgResultsTest:157 » NoClassDefFound Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
[ERROR]   SlackSlashCommandTest.handlesSearchErrorTest:126 » NoClassDefFound Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
[ERROR]   SlackSlashCommandTest.onlyAcceptsPostRequestsTest:86 » NoClassDefFound Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
[ERROR]   SlackSlashCommandTest.recognizesValidSlackTokenTest:113 » ExceptionInInitializer
[ERROR]   SlackSlashCommandTest.requiresSlackAuthHeadersTest:100 » NoClassDefFound Could not initialize class com.google.api.services.kgsearch.v1.Kgsearch
```

**Comment by Neenu1995** [comment]
There is a [newer version](https://search.maven.org/artifact/com.google.apis/google-api-services-kgsearch/v1-rev20200809-2.0.0/jar) of the library: v1-rev20200809-2.0.0

**Comment by Neenu1995** [comment]
If it is a version issue, this PR should fix it.
