### ISSUE TITLE
appengine-java8/multitenancy test(s) are failing

### ISSUE THREAD

**Issue by minherz** [GoogleCloudPlatform/java-docs-samples#8961]
#### Description

After the dependency upgrades in #8919 one or more tests under [appengine-java8/multitenancy][1] fail in Java 11 ([sponge][s11]) and Java 17 ([sponge][s17]).

Based on the errors:

```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.079 s <<< FAILURE! - in com.example.appengine.GreetingTest
[ERROR] com.example.appengine.GreetingTest.createSaveObject  Time elapsed: 0.041 s  <<< ERROR!
java.lang.IllegalStateException: You are attempting to initialize the singleton ObjectifyFactory more than once
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at com.googlecode.objectify.ObjectifyService.init(ObjectifyService.java:51)
	at com.googlecode.objectify.ObjectifyService.init(ObjectifyService.java:44)
	at com.example.appengine.GreetingTest.setUp(GreetingTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

[ERROR] com.example.appengine.GreetingTest.createSaveObject  Time elapsed: 0.043 s  <<< ERROR!
java.lang.NullPointerException
	at com.example.appengine.GreetingTest.tearDown(GreetingTest.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
```

the problem is in the way the `ObjectifyService` object is used. It is possible that `ObjectifyService.init` should be called once per all tests and not for every test.

[1]: https://github.com/renovate-bot/java-docs-samples/tree/7ef3ac48409470194438b459e86ab054b975a96c/appengine-java8/multitenancy
[s11]: https://btx-internal.corp.google.com/invocations/b28f9f6f-ea75-4c62-bd5d-48572c227087/targets/cloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava11%2Fpresubmit;config=default/log
[s17]: https://btx-internal.corp.google.com/invocations/52c67d76-564f-4311-bd6a-23c541f5ac5e/targets/cloud-devrel%2Fjava%2Fjava-docs-samples%2Fjava17%2Fpresubmit;config=default/log

**Comment by minherz** [comment]
@ ludoch feel free to reassign it to another team member of @GoogleCloudPlatform/serverless-runtimes team.

**Comment by ludoch** [comment]
Maybe @stickfigure  can help?

**Comment by minherz** [comment]
@ludoch I cannot find @stickfigure in the list of registered users. Does he work for Google?
Is it possible that @GoogleCloudPlatform/serverless-runtimes does not own the code samples for appengine?

**Comment by ludoch** [comment]
He is the Objectify main developer.

**Comment by ludoch** [comment]
Also, look at the sample history to find the folks who worked on it. (some are not googlers anymore). None from runtimes team...

**Comment by ludoch** [comment]
Finally, all the code under appengine-java8 should not be updated to a newer JDK, but should be cloned under equivalent java11 or java17 appengine runtimes directories. 
So not sure what this https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8919 is doing, but it should not modify appengine-java8 samples.

**Comment by stickfigure** [comment]
I added a sanity check to prevent the ObjectifyService from being initialized more than once (which is not something that should be done normally). Let me look over the multitenancy test and I'll ever remove that constraint or submit a PR here to update the sample.

**Comment by stickfigure** [comment]
After further consideration, I removed the (new) constraint and released Objectify 6.1.1 without it. So if you bump the Objectify version, this test should work again. Sorry about that, the perils of using statics...

**Comment by minherz** [comment]
> Finally, all the code under appengine-java8 should not be updated to a newer JDK, but should be cloned under equivalent java11 or java17 appengine runtimes directories. So not sure what this #8919 is doing, but it should not modify appengine-java8 samples.

@ludoch Where can I find documentation about this decision? It looks like a huge overload. It will be helpful to learn the reasons behind it.

**Comment by minherz** [comment]
> After further consideration, I removed the (new) constraint and released Objectify 6.1.1 without it. So if you bump the Objectify version, this test should work again. Sorry about that, the perils of using statics...

@stickfigure where these changes are submitted?

**Comment by stickfigure** [comment]
@minherz https://github.com/objectify/objectify/commits/master/

**Comment by ludoch** [comment]
Please update https://github.com/renovate-bot/java-docs-samples/blob/7ef3ac48409470194438b459e86ab054b975a96c/appengine-java8/multitenancy/pom.xml#L79 to 6.1.1

**Comment by minherz** [comment]
The tests were reestated ([#ecee6db][1]) and passed on Java8 and Java11 runtimes. Marking this issue as fixed.

[1]: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8971/commits/ecee6db479cd5d8c82d954f2c280249fa685b899
