### ISSUE TITLE
Pub/Sub Publish does not work in AppEngine (emulator) on Windows

### ISSUE THREAD

**Issue by dzlier-gcp** [GoogleCloudPlatform/java-docs-samples#977]
Reading messages from subscriptions works fine. However, when running Pub/Sub Publish commands on AppEngine Standard (Windows machine) there is a thread related 500 error.

	java.lang.RuntimeException: Couldn't invoke ThreadManager.currentRequestThreadFactory
		at com.google.common.util.concurrent.MoreExecutors.platformThreadFactory(MoreExecutors.java:765)
		at com.google.common.util.concurrent.MoreExecutors.newThread(MoreExecutors.java:807)
		at com.google.common.util.concurrent.MoreExecutors$Application.addDelayedShutdownHook(MoreExecutors.java:190)
		at com.google.common.util.concurrent.MoreExecutors$Application.getExitingScheduledExecutorService(MoreExecutors.java:182)
		at com.google.common.util.concurrent.MoreExecutors$Application.getExitingScheduledExecutorService(MoreExecutors.java:217)
		at com.google.common.util.concurrent.MoreExecutors.getExitingScheduledExecutorService(MoreExecutors.java:162)
		at com.google.api.gax.core.InstantiatingExecutorProvider.getExecutor(InstantiatingExecutorProvider.java:51)
		at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:132)
		at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:85)
		at com.google.cloud.pubsub.v1.Publisher$Builder.build(Publisher.java:661)
		at com.example.appengine.translate_pubsub.PubSubPublish.doPost(PubSubPublish.java:40)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
		at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:134)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
		at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
		at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
		at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
		at com.google.appengine.tools.development.jetty9.StaticFileFilter.doFilter(StaticFileFilter.java:123)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
		at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
		at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
		at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
		at com.google.appengine.tools.development.DevAppServerRequestLogFilter.doFilter(DevAppServerRequestLogFilter.java:44)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
		at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
		at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
		at org.eclipse.jetty.server.Server.handle(Server.java:534)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
		at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
		at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
		at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
		at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.ClassNotFoundException: com.google.appengine.api.ThreadManager
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:196)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:264)
		at com.google.common.util.concurrent.MoreExecutors.platformThreadFactory(MoreExecutors.java:758)
		... 55 more

**Comment by lesv** [comment]
So you are talking about the EMULATOR, not GAE/standard.

**Comment by dzlier-gcp** [comment]
I have run mvn appengine:deploy and it doesn't work on the live version either. I was just saying I am working on a windows laptop.

**Comment by kurtisvg** [comment]
Notice: this issue has been closed because it has been inactive for 192 days. You may reopen this issue if it has been closed in error.
