### ISSUE TITLE
Streaming gRPC for google-client java

### ISSUE THREAD

**Issue by awesomegtrr** [GoogleCloudPlatform/java-docs-samples#983]
The samples doesn't work. I got this error. After getting the samples and the dependencies, this is what I get. Not sure what am I missing. Please help?

exception in thread "main" java.lang.IllegalStateException: Missing required properties: totalTimeout initialRetryDelay retryDelayMultiplier maxRetryDelay initialRpcTimeout rpcTimeoutMultiplier maxRpcTimeout
at com.google.api.gax.retrying.AutoValue_RetrySettings$Builder.autoBuild(AutoValue_RetrySettings.java:295)
at com.google.api.gax.retrying.RetrySettings$Builder.build(RetrySettings.java:237)
at com.google.api.gax.rpc.UnaryCallSettings$Builder.(UnaryCallSettings.java:105)
at com.google.api.gax.rpc.UnaryCallSettings.newUnaryCallSettingsBuilder(UnaryCallSettings.java:79)
at com.google.cloud.speech.v1.SpeechSettings$Builder.(SpeechSettings.java:261)
at com.google.cloud.speech.v1.SpeechSettings$Builder.createDefault(SpeechSettings.java:277)
at com.google.cloud.speech.v1.SpeechSettings$Builder.access$000(SpeechSettings.java:207)
at com.google.cloud.speech.v1.SpeechSettings.newBuilder(SpeechSettings.java:183)
at com.google.cloud.speech.v1.SpeechClient.create(SpeechClient.java:117)

**Comment by lesv** [comment]
@dzlier-gcp FYI

**Comment by awesomegtrr** [comment]
This is what I did: 

`FileInputStream credentialsStream = new FileInputStream("tBuddy-7929bfa41652.json");
        GoogleCredentials credentials = GoogleCredentials.fromStream(credentialsStream);
        FixedCredentialsProvider credentialsProvider = FixedCredentialsProvider.create(credentials);
        
        SpeechSettings speechSettings
                = SpeechSettings.newBuilder()
                        .setCredentialsProvider(credentialsProvider)
                        .build();

        SpeechClient speech = SpeechClient.create(speechSettings);`

**Comment by dzlier-gcp** [comment]
Working on this today.
